
###
GET http://localhost:3333/api/v1/phones HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3333/api/v1/phones/11 HTTP/1.1
Content-Type: application/json

####

# Authorization: atighloveljene eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTgsIm5hbWUiOiJhdGlnaCIsImVtYWlsIjoiZWxhdGlnaEBEUzI0LmNvbSIsInVzZXJuYW1lIjoiYXRpZ2giLCJpYXQiOjE2MjUxNDM2NjMsImV4cCI6MTYyNTE0NDI2M30.5m-AJcB5WIDS8iGgHZOFMXKcadtZbAR817IdCvnBMk8
POST  http://localhost:3333/api/v1/phones/add-phone HTTP/1.1
Content-Type: application/json

{
    "image":"https://images.unsplash.com/photo-1600262606369-acb8a2cf69fb?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=934&q=80",
    "name":"Iphone 12 pro ",
    "brand":"Apple",
    "isUsed":true,
    "memory":120,
    "price":26000,
    "description":"description",
    "inStock":true,
    "imei":"AA-BBBBBB-CCCCCC-D",
    "quantity":3
}
###
PUT http://localhost:3333/api/v1/phones/update-phone/5  HTTP/1.1
Content-Type: application/json

{
    "image":"https://images.unsplash.com/photo-1603891128711-11b4b03bb138?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
    "name":"Iphone 11 ",
    "brand":"Apple",
    "isUsed":true,
    "memory":255,
    "price":190,
    "description":"description for iphone 11",
    "inStock":true
}
####
DELETE  http://localhost:3333/api/v1/phones/delete-phone/7  HTTP/1.1
Content-Type: application/json

####
POST  http://localhost:3333/api/v1/auth/login  HTTP/1.1
Content-Type: application/json

{
   "email":"elatigh@DS24.com", 
    "password":"atigh"
}
####


GET http://localhost:3333/api/v1/auth/users  HTTP/1.1
Content-Type: application/json


####
POST http://localhost:3333/api/v1/auth/sign-up  HTTP/1.1
Content-Type: application/json

{
    "name":"atigh", 
    "email":"elatigh@DS24.com", 
    "password":"atigh", 
    "username":"etfaghaoubeid"
}
###
GET http://localhost:3333/api/v1/auth/logout  HTTP/1.1
Content-Type: application/json

###
POST http://localhost:3333/api/v1/phones/add-accessory  HTTP/1.1
Content-Type: application/json

{
    "image":"image url",
    "name":"name",
    "brand":"brand",
    "isUsed":false,
    "memory":255,
    "price":3444,
    "description":"description",
    "inStock":true
}
####
GET http://localhost:3333/api/v1/accesories HTTP/1.1
Content-Type: application/json

####
GET http://localhost:3333/api/v1/accesories/2 HTTP/1.1
Content-Type: application/json

####

DELETE  http://localhost:3333/api/v1/accesories/4  HTTP/1.1
Content-Type: application/json

####
